apiVersion: v1
kind: Namespace
metadata:
  name: funlynk
  labels:
    name: funlynk
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: funlynk-quota
  namespace: funlynk
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "20"
    configmaps: "20"
    pods: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: funlynk-limits
  namespace: funlynk
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
  - max:
      cpu: "2"
      memory: "2Gi"
    min:
      cpu: "50m"
      memory: "64Mi"
    type: Container
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: funlynk-backend
  namespace: funlynk
  labels:
    app: backend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: funlynk-admin-dashboard
  namespace: funlynk
  labels:
    app: admin-dashboard
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: funlynk
  name: funlynk-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: funlynk-rolebinding
  namespace: funlynk
subjects:
- kind: ServiceAccount
  name: funlynk-backend
  namespace: funlynk
- kind: ServiceAccount
  name: funlynk-admin-dashboard
  namespace: funlynk
roleRef:
  kind: Role
  name: funlynk-role
  apiGroup: rbac.authorization.k8s.io
